### PR TITLE
[Req. for Comments] Add more options to env config

### PR DESCRIPTION
**Pull request by ck**
This is not so much of a pull request then a feedback request on my first try to adding different options for defining environments (including default environments when none are specified in the `project.clj` file). 

Since I re-factored my code multiple times (trying to thrive for decent Clojure code), I decided to add some tests.

I probably should add that I was going back and forth between just filling in the values for the passed in environment and for all defined environments. In the end I decided to go with the later, since it seemed clearer and less code (esp. in the case there are no `:environments` defined).

Again, any comments on the options and the code is appreciated,

-ck

### CODE REVIEW

**Comment by weavejester** [comment]
Merged in.

The code looks mostly fine. The only odd bit is the when-let and not-empty part. I think just change that to an if-let, as when-let is generally reserved for side effects, and not-empty I don't think is necessary in this case, as nil is treated as false anyway.

I may also tweak the development cname-prefix to be "<project name>-dev", as "-development" is a little too long.

**Comment by weavejester** [comment]
Oh, I didn't notice that this wasn't a real pull request. But I tested it and it all seemed to work, so...

**Comment by weavejester** [comment]
Sorry for all the comment-spam. The only other thing I'd consider changing is the `update-project` function. Instead of changing the project map, it's probably better to have a function to get the environment.

**Comment by ck** [comment]
No problem, any feedback is welcome. Two comments:
- I used the `not-empty` to also cover the case of `:environments []`.
- I was thinking about a function that gets the environment, but thought a mod to the project map is less obtrusive to the current code  

-ck

**Comment by weavejester** [comment]
- I figure that if the user explicitly sets `:environemnts` to `[]`, then they shouldn't be surprised if there are no environments. It's only when the `:environments` key is not set does it use the defaults. So it's good that you're worrying about edge cases, but in this case I don't think we need to worry :)
- Yeah, a project map is less obtrusive, and there's really not much to choose between them. But I believe it's considered better practice in Lisp to prefer more functions over more data structures. I've written some code I'm just about to commit that uses functions instead (but as you say, it required a little more alterations to the source). I don't think it matters hugely though; if I didn't have a bit of time spare, I probably wouldn't have bothered changing it.

**Pull request closed without merging**
