### PR TITLE
Added support for eu-central-4, updated clojure, updated aws-java-sdk

### PR DESCRIPTION
**Pull request by kremers**
Support eu-central-4
Update clojure to 1.6.0
Update aws-java-sdk to 1.10.5.1

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch.

These ideally should be three separate commits. The Clojure version should really be removed, not updated, since this is a plugin. Also, don't update the project version.

Can you explain the addition of the jackson dependencies?

**Comment by kremers** [comment]
Running newer amazon sdk packages leads to errors during runtime. Some methods used by jackson are not available in newer versions. So the version needs to be explicit.

For further information see: https://github.com/mcohen01/amazonica/issues/135

See 'lein beanstalk info' output:

Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:472)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:391)
        at com.amazonaws.util.json.Jackson.<clinit>(Jackson.java:32)
...

Thank you for the information about the removal of the Clojure dependency.

The older SDK does not work with newer aws regions since there are no enums defined (for example for eu-central-1 Frankfurt). 

For things to work well with the new AWS-SDK there are some additional changes needed like setting the worker or webserver tier. An instance ID has also to be passed (Otherwise you will see the error: Environment must have instance profile associated with it.)

**Comment by kremers** [comment]
Please discard this pull request in favour of my 2'nd request which is cleaner, including rebased commits and left out merge commits.

**Comment by weavejester** [comment]
You don't need to create a new pull request in order to change the commits in it. The pull request is associated with a branch, and a branch in git is just a pointer to a particular commit that can be changed at will.

**Pull request closed without merging**
