### PR TITLE
More info

### PR DESCRIPTION
**Pull request by ck**
Thanks for your feedback on my first try. All made sense and it works like a charm with my app.

I added another feature to provide information for the application itself when not passing in an environment to the `info` option.

-ck

### CODE REVIEW

**Comment by weavejester** [comment]
I'll take a look in more detail at this tonight, but it looks like your pull request includes all of your old commits as well, so it'll be a little more difficult to merge in your changes (I'll have to cherry-pick them individually).

As a general rule, it's a good idea to develop patches in a separate branch, and keep your master synced to the master of the main repository. Could you possibly redo your pull request so that it only includes the new commits?

**Comment by ck** [comment]
Sorry about that. I did rebase with your master and then merged it in. Not exactly sure what happened there. I will redo it with a branch and use branches from now on.

Again, sorry for the mess,

-ck

**Comment by ck** [comment]
Pull request has been replace by new and slimmer one.

**Comment by ck** [comment]
Pull request has been replace by new and slimmer one.

**Pull request closed without merging**
