### PR TITLE
Use env as cname

### PR DESCRIPTION
**Pull request by ck**
A small change. This will use the environment name as the preferred CNAME prefix. I found that useful, because otherwise AWS will create a URL name.

Fyi, I added this on top of the add-application-info branch.

-ck

### CODE REVIEW

**Comment by weavejester** [comment]
I was planning on making the environments hashes to solve this problem. e.g.

```
:beanstalk {:environments [{:name "production", :cname-prefix "myapp"}]}
```

Having a randomly created subdomain isn't actually that bad in practise, as most of the time you'll want to bind a cname to the generated environment anyway.

**Comment by ck** [comment]
Hmm, I like that. Stupid question, why not make the environment name be the key for the env config, i.e.

```
beanstalk {:environments {"production" {:cname-prefix "myapp"}}}
```

I still like the env default 'try' if not specified (I believe AWS tries to use the submitted name and will use the generated one otherwise). 

Again, just an idea,

-ck

**Comment by weavejester** [comment]
I was thinking environments could be specified as a single value, or as a map, e.g.

```
:beanstalk {:environments [development {:name production, :cname-prefix "myapp"}]}
```

I wonder whether an environment name needs to be unique. If it doesn't it might make sense for the default cname-prefix (which does have to be unique) to be `(str (:name project) - env-name)`. Then you could have a "dev" environment for "myapp", and it would deploy by default to "myapp-dev", which seems sensible.

We could even have a default set of environments (development, test and production) which could then be overridden if necessary. But if the defaults are good enough, most people will probably stick with that and we'll have reduced the amount of setup code.

**Comment by ck** [comment]
I like your idea of `<project name>-<env-name>` as default environment name (with the option to override it) and then the derived CNAME prefix default (again with the ability to override). With that we have the following cases (for a myapp project.clj)

```
:beanstalk {:environments [development]}
=> App Name     : myapp
=> Env Name     : myapp-development
=> CNAME prefix : myapp-development

:beanstalk {:environments [development {:name theapp}]}
=> App Name     : myapp
=> Env Name     : theapp-development
=> CNAME prefix : theapp-development

:beanstalk {:environments [development {:cname-prefix "myapp-secret"}]}
=> App Name     : myapp
=> Env Name     : myapp-development
=> CNAME prefix : myapp-secret

:beanstalk {:environments [development {:name theapp, :cname-prefix "myapp-secret"}]}
=> App Name     : myapp
=> Env Name     : theapp-development
=> CNAME prefix : myapp-secret
```

I hope I interpreted your comment right, but feel free to tell me I am crazy ;).

-ck

**Comment by weavejester** [comment]
I was more thinking that a environment could be represented as a symbol _or_ a map. e.g.

```
(for [env (-> project :aws :beanstalk :environments)]
  (if (map? env)
    env
    {:name env}))
```

And then something to add in default values into the map if they're missing.

**Comment by ck** [comment]
I like that (like I mentioned before, I am still learning the finer points of Clojure).

-ck

**Comment by ck** [comment]
Sorry to bother you, but before I start taking a crack at it, I want to make sure this is what you have in mind for the environment configuration:

Elastic Beanstalk environments can be define multipe ways in
the `project.clj` file.

If no environments are specified, lein-beanstalk will create three
default environments
- development
- staging
- production

To override the default behavior, either have `:environments`
point to vector of envionment symbols

```
:aws {:beanstalk {:environments [myapp-staging myapp-production]
                  ...}
      ...}
```

or to a vector of maps

```
:aws {:beanstalk {:environments [{:name "myapp-production" ...}
                                 {:name "myapp-staging" ...}]
                  ...}
      ...}
```

In either case the following two environents will be created
- myapp-staging
- myapp-production

The second option allows to explicitly specify the CNAME prefix for that
environment

```
:aws {:beanstalk {:environments [{:name "myapp-production"
                                  :canme-prefix "myapp"}
                                 {:name "myapp-staging"
                                  :cname-prefix "myapp-demo"}]
                  ...}
      ...}
```

By default the CNAME prefix is `<project-name>-<environment>`.

-ck

**Comment by weavejester** [comment]
I'm not sure about the defaults. Having "myapp-development" seems too long, and production URLs are usually just "myapp". So perhaps these would be good defaults:

```
[{:name "development", :cname-prefix "myapp-dev"}
 {:name "staging", :cname-prefix "myapp-staging"}
 {:name "production", :cname-prefix "myapp"}]
```

What do you think?

**Comment by ck** [comment]
You are right. The defaults make a lot more sense.

I'll start working on it then, unless you already started or have it done.

-ck

**Comment by weavejester** [comment]
No, not yet. I've been a little snowed under with work within the last few days. You're welcome to start on this.

**Pull request closed without merging**
